/** \file FullWeighting.h
 * \author <a href="mailto:mail@jirikraus.de">Jiri Kraus</a>
 * \brief Contains the interface of the class FullWeighting.
 */
#ifndef FULLWEIGHTING_H_
#define FULLWEIGHTING_H_

#include "Restriction.h"
 
namespace mg
{

/**
 * \brief FullWeighting is a 2D restriction operator
 * 
 * FullWeighting is a representation of a 2D restriction operator that uses
 * full weighting to do its job.
 */
class FullWeighting : public mg::Restriction
{
private:
    const Precision weight_;
    const NumericArray i_;
    const PositionArray jx_;
    const PositionArray jy_;
    //initilize i_, makes it possible to make i_ const
    NumericArray initI_(Precision weight) const
    {
        const Precision t[]={weight/4,weight/8,weight/8,weight/8,weight/8,
                             weight/16,weight/16,weight/16,weight/16};
        return NumericArray(t,9);
    }
    //initilize jx_, makes it possible to make jx_ const
    PositionArray initJX_() const
    {
        const int t[]={0,-1,0,1,0,-1,1,1,-1};
        return PositionArray(t,9);
    }
    //initilize jy_, makes it possible to make jy_ const
    PositionArray initJY_() const
    {
        const int t[]={0,0,1,0,-1,1,1,-1,-1};
        return PositionArray(t,9);
    }
    //we don't want these autogenerated ctors and operators
    FullWeighting(const FullWeighting& rhs);
    FullWeighting& operator=(const FullWeighting& rhs);
public:
    /**
     * \brief The constructor of a FullWeighting object
     * 
     * FullWeighting constructs a FullWeighting object with:
     * \param[in] weight    the weight to do full weighting with (default 1.0)
     */
    FullWeighting(Precision weight = 1.0)
        : weight_(weight),i_(initI_(weight)), jx_(initJX_()), jy_(initJY_()) {}

    virtual ~FullWeighting(){}
    
    /**
     * \brief restriction() restricts the given vector to a smaller grid
     * 
     * restriction() restricts the given vector which represents a rectangular
     * grid to a smaller grid with the double step size with the full weighting
     * Operator.
     * 
     * \param[in] u                 the vector to restrict
     * \param[in] stencil           the stencil rep. of the pde needed
     *                              for matrix dep. Restrictions (not used)
     * \param[in] prolongate        Prolongation used, needed for matrix dep.
     *                              Restrictions (not used)
     * \param[in] nx                number of steps in x direction
     * \param[in] ny                number of steps in y direction
     * \throw std::domain_error     if nx or ny is not divedable by 2
     * \return                      a vector with the values on the restricted
     *                              grid
     */ 
    virtual DiscreteFunction restriction(
        const Problem& problem, const DiscreteFunction& u) const;
        
    const NumericArray& getI(
        const Position,
        const Index,
        const Index,
        const Index,
        const Index,
        const Stencil&) const
    {
        return i_;  
    }
    
    const PositionArray& getJx( const Position ) const
    {
        return jx_; 
    }
    
    const PositionArray& getJy( const Position ) const
    {
        return jy_;
    }
};

}

#endif /*FULLWEIGHTING_H_*/
