/** \file SevenPoint_interpolation.h
 * \author Benedikt Engbroks
 * \brief Contains the interface of the class SevenPoint_interpolation
 * 
 * This file contains the interface of SevenPoint_interpolation. The
 * implementation is in SevenPoint_interpolation.cpp
 */
#ifndef SEVENPOINT_INTERPOLATION_H_
#define SEVENPOINT_INTERPOLATION_H_

#include "Prolongation.h"

namespace mg
{

/**
 * \brief SevenPoint_interpolation is a 2D Prolongation Operator
 * 
 * SevenPoint_interpolation represents a 2D Prolongation Operator that uses
 * 7-point interpolation to do its job.
 */
class SevenPoint_interpolation : public mg::Prolongation
{
private:
	const std::valarray<precision> I;
	const std::valarray<int> J_x;
	const std::valarray<int> J_y;
	//initialize I, makes it possible to make I const
	std::valarray<precision> init_I() const
	{
		const precision t[] = {1.0,1.0/2,1.0/2,1.0/2,1.0/2,1.0/2,0.0,1.0/2,0.0};
		return std::valarray<precision>(t,9);
	}
	//initialize J_x, makes it possible to make J_x const
	std::valarray<int> init_J_x() const
	{
		const int t[] = {0,-1,0,1,0,-1,1,1,-1};
		return std::valarray<int>(t,9);
	}
	//initialize J_y, makes it possible to make J_y const
	std::valarray<int> init_J_y() const
	{
		const int t[] = {0,0,1,0,-1,1,1,-1,-1};
		return std::valarray<int>(t,9);
	}
	//we don't want these autogenerated contors and operators
	SevenPoint_interpolation(const SevenPoint_interpolation& rhs);
	SevenPoint_interpolation& operator=(const SevenPoint_interpolation& rhs);
public:
	SevenPoint_interpolation()
		: I(init_I()), J_x(init_J_x()), J_y(init_J_y()) {}
	virtual ~SevenPoint_interpolation() {}
	/**
	 * \brief prolong does a bicubic interpolation on the input vector
	 * 
	 * \param u		the vector representing a rectangel to prolongate
	 * \param Nx	Number of steps in x direction
	 * \param Ny	Number of steps in y direction
	 * \return 		a vector representing the prolongated rectangel of 
	 * 				size 2*(Nx+1)*2*(Ny+1)
	 */
	std::valarray<precision> prolong(const std::valarray<precision>& u,
									const Stencil& stencil,
									const size_t Nx,const size_t Ny) const;
	const std::valarray<precision>& get_I(const size_t, const size_t,
									const size_t, const size_t, const Stencil& stencil) const
	{
		return I;	
	}
	const std::valarray<int>& get_J_x() const
	{
		return J_x;	
	}
	const std::valarray<int>& get_J_y() const
	{
		return J_y;
	}
};

}

#endif /*SEVENPOINT_INTERPOLATION_H_*/
